services:
  backend:
    build:
      context: ./Backend/Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app_network

  nginx:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  app_network:
    driver: bridge
